[package]
name = "lightbeam"
version = "0.0.0"
authors = ["The Lightbeam Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
categories = ["wasm"]
keywords = ["webassembly", "wasm", "compile", "compiler", "jit"]
publish = false

[dependencies]
arrayvec = "0.4"
dynasm = "0.2.3"
dynasmrt = "0.2.3"
wasmparser = "0.21.6"
capstone = "0.5.0"
failure = "0.1.3"
failure_derive = "0.1.3"
wabt = "0.7"
lazy_static = "1.2"
quickcheck = "0.7"

[badges]
maintenance = { status = "experimental" }
